benchmarks:
- curl_curl_fuzzer_http
- freetype2_ftfuzzer
- harfbuzz_hb-shape-fuzzer
- lcms_cms_transform_fuzzer
concurrent_builds: 30
custom_seed_corpus_dir: null
description: null
docker_registry: gcr.io/fuzzbench
experiment: symcc-24h-aflmap
experiment_filestore: /tmp/experiment-data
fuzzers:
- symcc_mod_aflplusplus
- symcc_aflplusplus
git_hash: ad23966612feeb26ffd2730320cf8570ab04954c
local_experiment: true
max_total_time: 86400
measurers_cpus: null
micro_experiment: false
no_dictionaries: false
no_seeds: false
oss_fuzz_corpus: false
private: false
region_coverage: false
report_filestore: /tmp/report-data
runner_machine_type: n1-standard-1
runner_memory: 12GB
runner_num_cpu_cores: 1
runners_cpus: null
snapshot_period: 900
trials: 3
worker_pool_name: ''
